stages:
  - build

fedora-x86_64:
  stage: build
  image: registry.gitlab.gnome.org/gnome/gobject-introspection:v1
  script:
    - meson --prefix /usr --libdir /usr/lib64 --buildtype debug -Dcairo=true _build .
    - cd _build
    - ninja
    - meson test --print-errorlogs --suite=gobject-introspection --no-suite=glib
  except:
    - tags
  artifacts:
    when: on_failure
    name: "gi-_${CI_COMMIT_REF_NAME}"
    paths:
      - "${CI_PROJECT_DIR}/_build/meson-logs"
