image: ebassi/gitlab-gi:latest

stages:
  - build

build-job:
  stage: build
  script:
    - meson --prefix /usr --libdir /usr/lib64 --buildtype debug --werror -Dcairo=true _build .
    - cd _build
    - ninja
    - meson test
  except:
    - tags
  artifacts:
    when: on_failure
    name: "glib-_${CI_COMMIT_REF_NAME}"
    paths:
      - "${CI_PROJECT_DIR}/_build/meson-logs"
